FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json ./
RUN npm install
COPY .env.local ./
COPY App.tsx ./App.tsx
COPY constants.tsx ./constants.tsx
COPY index.html ./index.html
COPY index.tsx ./index.tsx
COPY tsconfig.json ./tsconfig.json
COPY types.ts ./types.ts
COPY vite.config.ts ./vite.config.ts
COPY views ./views
RUN npm run build

FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
