FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY tsconfig.json vite.config.ts ./
COPY index.html ./
COPY src ./src
COPY public ./public

COPY constants.tsx types.ts ./

RUN npm run build

FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
RUN chmod -R 755 /usr/share/nginx/html
EXPOSE 80
CMD ["/bin/sh", "-c", "nginx -t && exec nginx -g 'daemon off;'"]
